# Generated by Django 5.0.9 on 2024-11-21 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('food_description', models.TextField()),
                ('food_image', models.ImageField(upload_to='food_images/')),
                ('location', models.CharField(max_length=255)),
                ('expiration_info', models.DateTimeField()),
                ('status', models.CharField(default='Available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('user_type', models.CharField(choices=[('Individual', 'Individual'), ('NGO', 'NGO'), ('Restaurant', 'Restaurant')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('Like', 'Like'), ('Bookmark', 'Bookmark'), ('Share', 'Share')], max_length=20)),
                ('interaction_date', models.DateTimeField(auto_now_add=True)),
                ('food_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='api.foodpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='api.user')),
            ],
        ),
        migrations.AddField(
            model_name='foodpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_posts', to='api.user'),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donation_date', models.DateTimeField(auto_now_add=True)),
                ('food_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='api.foodpost')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('food_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='api.foodpost')),
                ('claimer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='api.user')),
            ],
        ),
    ]
